//! Parametric equaliser: seven bands plus a frequency-response readout.
//!
//! PLAN §1.3 requires "参数均衡器（≥ 7 段，含频谱显示）". This module provides
//! the seven bands and the response computation the display needs;
//! [`super::spectrum`] provides the analysis.
//!
//! # Why seven bands are generated rather than written out
//!
//! Every band is the same biquad with different coefficients, so the parameter
//! table is built by a loop over [`BAND_COUNT`] rather than by 28 hand-written
//! descriptors. That is what keeps "band 4's frequency" and "band 4's type" in
//! step: they are generated by the same index.
//!
//! # Band layout
//!
//! Band 0 is a low shelf, band 6 a high shelf, and bands 1..=5 are peaking.
//! That is the layout every parametric EQ uses, and it means a user who only
//! touches the outer two knobs gets a tone control rather than a comb.
//!
//! # Real-time safety
//!
//! All seven biquads are inline in the struct and all scratch is allocated in
//! `prepare`. `process` performs no allocation.

use super::super::buffer::{AudioBuffer, RenderContext};
use super::super::{
    clamp_parameter, sanitize_wet, EffectCategory, EffectDescriptor, EffectProcessor,
};
use super::super::filter::biquad::{Biquad, FilterMode};
use crate::automation::parameter::{
    parameter_flags, ParameterAddress, ParameterDescriptor, ParameterUnit,
};

/// Number of bands. PLAN §1.3 requires at least seven.
pub const BAND_COUNT: usize = 7;

/// Parameters per band: enabled, type, frequency, gain, Q.
pub const PARAMS_PER_BAND: u16 = 5;

/// First band's `enabled` ordinal.
pub const PARAM_BAND_BASE: u16 = 0;
/// Output trim in decibels.
pub const PARAM_OUTPUT_DB: u16 = PARAM_BAND_BASE + PARAMS_PER_BAND * BAND_COUNT as u16;
/// Wet/dry in percent.
pub const PARAM_MIX: u16 = PARAM_OUTPUT_DB + 1;

/// Total published parameters.
pub const PARAM_COUNT: u16 = PARAM_MIX + 1;

/// Maximum channels the per-channel state covers.
const MAX_CHANNELS: usize = 2;

/// The effect's static description.
pub static DESCRIPTOR: EffectDescriptor = EffectDescriptor {
    kind: super::super::registry::KIND_EQ_PARAMETRIC,
    key: "parametric_eq",
    label: "Parametric EQ",
    category: EffectCategory::Equalizer,
    first_param: 0,
    param_count: PARAM_COUNT,
    has_latency: false,
    is_analysis_only: false,
};

/// The default filter type for band `index`.
///
/// The outer bands are shelves and the inner ones peaking, which is the layout
/// that makes the two end knobs useful on their own.
#[must_use]
pub const fn default_mode_for_band(index: usize) -> FilterMode {
    if index == 0 {
        FilterMode::LowShelf
    } else if index + 1 == BAND_COUNT {
        FilterMode::HighShelf
    } else {
        FilterMode::Peaking
    }
}

/// The default centre frequency for band `index`, in hertz.
///
/// Spread logarithmically from 80 Hz to 12 kHz so the seven bands cover the
/// audible range evenly rather than bunching at the bottom.
#[must_use]
pub fn default_frequency_for_band(index: usize) -> f32 {
    const LOW: f32 = 80.0;
    const HIGH: f32 = 12_000.0;
    if BAND_COUNT <= 1 {
        return LOW;
    }
    let t = index as f32 / (BAND_COUNT - 1) as f32;
    // Geometric interpolation, expressed through the shared `powf` so the
    // module needs no `std` math.
    LOW * super::super::util::dsp::powf(HIGH / LOW, t)
}

/// The default Q for band `index`.
#[must_use]
pub const fn default_q_for_band(index: usize) -> f32 {
    if index == 0 || index + 1 == BAND_COUNT {
        // Shelves use a gentler slope so they behave like tone controls.
        0.707
    } else {
        1.0
    }
}

/// The ordinal of the `field`-th parameter of `band`.
///
/// `field` 0..4 is enabled / type / frequency / gain / Q.
#[must_use]
pub const fn band_ordinal(band: usize, field: u16) -> u16 {
    PARAM_BAND_BASE + band as u16 * PARAMS_PER_BAND + field
}

/// Builds the full parameter table for an instance at `address`.
#[must_use]
pub fn parameter_table(address: ParameterAddress) -> [ParameterDescriptor; PARAM_COUNT as usize] {
    let slot = address.effect_slot();
    let channel = address.index;
    let at = |sub: u16| ParameterAddress::effect(channel, slot, sub);

    // Build with a fixed-size array and index assignment rather than a Vec, so
    // the table stays a plain array the engine can hold inline.
    let mut table = [ParameterDescriptor {
        address: at(0),
        key: "",
        label: "",
        unit: ParameterUnit::Linear,
        flags: 0,
        min_value: 0.0,
        max_value: 1.0,
        default_value: 0.0,
        smoothing_ms: 0.0,
    }; PARAM_COUNT as usize];

    let mut band = 0;
    while band < BAND_COUNT {
        let default_mode = default_mode_for_band(band);
        // A band is enabled by default only if it is not a do-nothing peaking
        // band at 0 dB. Bands 1/2/3/4/5 start enabled so a user can grab one
        // immediately; the 0 dB default means they are transparent until moved.
        table[band_ordinal(band, 0) as usize] = ParameterDescriptor {
            address: at(band_ordinal(band, 0)),
            key: BAND_ENABLED_KEYS[band],
            label: BAND_ENABLED_LABELS[band],
            unit: ParameterUnit::Enumeration,
            flags: parameter_flags::DISCRETE,
            min_value: 0.0,
            max_value: 1.0,
            default_value: 1.0,
            smoothing_ms: 0.0,
        };
        table[band_ordinal(band, 1) as usize] = ParameterDescriptor {
            address: at(band_ordinal(band, 1)),
            key: BAND_TYPE_KEYS[band],
            label: BAND_TYPE_LABELS[band],
            unit: ParameterUnit::Enumeration,
            flags: parameter_flags::DISCRETE,
            min_value: 0.0,
            max_value: 7.0,
            default_value: default_mode.as_u32() as f32,
            smoothing_ms: 0.0,
        };
        table[band_ordinal(band, 2) as usize] = ParameterDescriptor {
            address: at(band_ordinal(band, 2)),
            key: BAND_FREQ_KEYS[band],
            label: BAND_FREQ_LABELS[band],
            unit: ParameterUnit::Hertz,
            flags: parameter_flags::AUTOMATABLE
                | parameter_flags::LOGARITHMIC
                | parameter_flags::SMOOTHED,
            min_value: 20.0,
            max_value: 20_000.0,
            default_value: default_frequency_for_band(band),
            smoothing_ms: 15.0,
        };
        table[band_ordinal(band, 3) as usize] = ParameterDescriptor {
            address: at(band_ordinal(band, 3)),
            key: BAND_GAIN_KEYS[band],
            label: BAND_GAIN_LABELS[band],
            unit: ParameterUnit::Decibels,
            flags: parameter_flags::AUTOMATABLE
                | parameter_flags::BIPOLAR
                | parameter_flags::SMOOTHED,
            min_value: -24.0,
            max_value: 24.0,
            default_value: 0.0,
            smoothing_ms: 15.0,
        };
        table[band_ordinal(band, 4) as usize] = ParameterDescriptor {
            address: at(band_ordinal(band, 4)),
            key: BAND_Q_KEYS[band],
            label: BAND_Q_LABELS[band],
            unit: ParameterUnit::Linear,
            flags: parameter_flags::AUTOMATABLE | parameter_flags::SMOOTHED,
            min_value: 0.1,
            max_value: 18.0,
            default_value: default_q_for_band(band),
            smoothing_ms: 15.0,
        };
        band += 1;
    }

    table[PARAM_OUTPUT_DB as usize] = ParameterDescriptor {
        address: at(PARAM_OUTPUT_DB),
        key: "output_db",
        label: "Output",
        unit: ParameterUnit::Decibels,
        flags: parameter_flags::AUTOMATABLE | parameter_flags::BIPOLAR | parameter_flags::SMOOTHED,
        min_value: -24.0,
        max_value: 24.0,
        default_value: 0.0,
        smoothing_ms: 10.0,
    };
    table[PARAM_MIX as usize] = ParameterDescriptor {
        address: at(PARAM_MIX),
        key: "mix",
        label: "Mix",
        unit: ParameterUnit::Percent,
        flags: parameter_flags::AUTOMATABLE | parameter_flags::SMOOTHED,
        min_value: 0.0,
        max_value: 100.0,
        default_value: 100.0,
        smoothing_ms: 10.0,
    };
    table
}

// Per-band keys, generated by hand so each is a distinct stable string. Kept
// as arrays so the loop above stays a loop.
const BAND_ENABLED_KEYS: [&str; BAND_COUNT] = [
    "band1_enabled",
    "band2_enabled",
    "band3_enabled",
    "band4_enabled",
    "band5_enabled",
    "band6_enabled",
    "band7_enabled",
];
const BAND_ENABLED_LABELS: [&str; BAND_COUNT] = [
    "Band 1 On",
    "Band 2 On",
    "Band 3 On",
    "Band 4 On",
    "Band 5 On",
    "Band 6 On",
    "Band 7 On",
];
const BAND_TYPE_KEYS: [&str; BAND_COUNT] = [
    "band1_type",
    "band2_type",
    "band3_type",
    "band4_type",
    "band5_type",
    "band6_type",
    "band7_type",
];
const BAND_TYPE_LABELS: [&str; BAND_COUNT] = [
    "Band 1 Type",
    "Band 2 Type",
    "Band 3 Type",
    "Band 4 Type",
    "Band 5 Type",
    "Band 6 Type",
    "Band 7 Type",
];
const BAND_FREQ_KEYS: [&str; BAND_COUNT] = [
    "band1_hz",
    "band2_hz",
    "band3_hz",
    "band4_hz",
    "band5_hz",
    "band6_hz",
    "band7_hz",
];
const BAND_FREQ_LABELS: [&str; BAND_COUNT] = [
    "Band 1 Freq",
    "Band 2 Freq",
    "Band 3 Freq",
    "Band 4 Freq",
    "Band 5 Freq",
    "Band 6 Freq",
    "Band 7 Freq",
];
const BAND_GAIN_KEYS: [&str; BAND_COUNT] = [
    "band1_gain_db",
    "band2_gain_db",
    "band3_gain_db",
    "band4_gain_db",
    "band5_gain_db",
    "band6_gain_db",
    "band7_gain_db",
];
const BAND_GAIN_LABELS: [&str; BAND_COUNT] = [
    "Band 1 Gain",
    "Band 2 Gain",
    "Band 3 Gain",
    "Band 4 Gain",
    "Band 5 Gain",
    "Band 6 Gain",
    "Band 7 Gain",
];
const BAND_Q_KEYS: [&str; BAND_COUNT] = [
    "band1_q",
    "band2_q",
    "band3_q",
    "band4_q",
    "band5_q",
    "band6_q",
    "band7_q",
];
const BAND_Q_LABELS: [&str; BAND_COUNT] = [
    "Band 1 Q",
    "Band 2 Q",
    "Band 3 Q",
    "Band 4 Q",
    "Band 5 Q",
    "Band 6 Q",
    "Band 7 Q",
];

/// One band's user-facing settings.
#[derive(Debug, Clone, Copy)]
pub struct BandSettings {
    /// Whether the band is in circuit.
    pub enabled: bool,
    /// Filter type.
    pub mode: FilterMode,
    /// Centre or corner frequency, hertz.
    pub frequency_hz: f32,
    /// Boost or cut, decibels.
    pub gain_db: f32,
    /// Quality factor.
    pub q: f32,
}

impl BandSettings {
    /// The defaults for `band`.
    #[must_use]
    pub fn defaults(band: usize) -> Self {
        Self {
            enabled: true,
            mode: default_mode_for_band(band),
            frequency_hz: default_frequency_for_band(band),
            gain_db: 0.0,
            q: default_q_for_band(band),
        }
    }

    /// Whether this band currently alters the signal.
    ///
    /// A peaking band at exactly 0 dB is transparent, and a shelf at 0 dB has
    /// unity gain: skipping those saves four multiply-adds per sample each,
    /// which is measurable when seven bands are active on 128 tracks.
    #[must_use]
    pub fn is_audible(&self) -> bool {
        if !self.enabled {
            return false;
        }
        if self.mode.uses_gain() {
            self.gain_db.abs() > 1e-3
        } else {
            true
        }
    }
}

/// One channel's seven biquads.
#[derive(Debug, Clone, Copy)]
struct BandState {
    /// The filter section.
    filter: Biquad,
    /// The settings the section was designed from, so a redesign is only done
    /// when something actually changed.
    settings: BandSettings,
}

impl Default for BandState {
    fn default() -> Self {
        Self {
            filter: Biquad::default(),
            settings: BandSettings {
                enabled: false,
                mode: FilterMode::Peaking,
                frequency_hz: 1_000.0,
                gain_db: 0.0,
                q: 1.0,
            },
        }
    }
}

/// The parametric equaliser.
#[derive(Debug)]
pub struct ParametricEq {
    /// The published parameter table.
    table: [ParameterDescriptor; PARAM_COUNT as usize],
    /// Per-band user settings (band, not per channel: the EQ is linked stereo,
    /// which is what a channel insert wants).
    bands: [BandSettings; BAND_COUNT],
    /// Per-channel filter state.
    state: [[BandState; BAND_COUNT]; MAX_CHANNELS],
    /// Output trim in decibels.
    output_db: f32,
    /// Wet/dry in percent.
    mix_percent: f32,
    /// Wet/dry, `0..=1`.
    wet: f32,
    /// Bypass.
    bypassed: bool,
    /// Sample rate.
    sample_rate: f32,
    /// Preallocated dry snapshot.
    dry: alloc::vec::Vec<f32>,
    /// Preallocated capacity, for the `process` guard.
    max_block: usize,
}

impl Default for ParametricEq {
    fn default() -> Self {
        Self::new(ParameterAddress::effect(0, 0, 0))
    }
}

impl ParametricEq {
    /// Creates the effect for the slot at `address`.
    #[must_use]
    pub fn new(address: ParameterAddress) -> Self {
        let table = parameter_table(address);
        let mut bands = [BandSettings::defaults(0); BAND_COUNT];
        for (index, band) in bands.iter_mut().enumerate() {
            *band = BandSettings::defaults(index);
        }
        Self {
            table,
            bands,
            state: [[BandState::default(); BAND_COUNT]; MAX_CHANNELS],
            output_db: 0.0,
            mix_percent: 100.0,
            wet: 1.0,
            bypassed: false,
            sample_rate: 48_000.0,
            dry: alloc::vec::Vec::new(),
            max_block: 0,
        }
    }

    /// The current settings for `band`.
    #[must_use]
    pub fn band(&self, band: usize) -> Option<&BandSettings> {
        self.bands.get(band)
    }

    /// The overall magnitude response at `hz`, in decibels.
    ///
    /// Used by the UI's response curve. Summing the bands' dB responses is an
    /// approximation (the true response is the product of the transfer
    /// functions, which is exact in dB only when phases align) but it is what
    /// every equaliser display shows, and the error is well under a dB except
    /// where bands overlap heavily and cancel.
    #[must_use]
    pub fn response_db_at(&self, hz: f32) -> f32 {
        let mut total = self.output_db;
        for band in 0..BAND_COUNT {
            if !self.bands[band].is_audible() {
                continue;
            }
            total += self.state[0][band].filter.magnitude_db_at(hz, self.sample_rate);
        }
        total
    }

    /// Redesigns one band's biquad on every channel.
    fn redesign(&mut self, band: usize, channel: usize) {
        let settings = self.bands[band];
        self.state[channel][band].filter.design(
            settings.mode,
            settings.frequency_hz,
            settings.q,
            settings.gain_db,
            self.sample_rate,
        );
        self.state[channel][band].settings = settings;
    }

    /// Redesigns every band on every channel.
    fn redesign_all(&mut self) {
        for band in 0..BAND_COUNT {
            for channel in 0..MAX_CHANNELS {
                self.redesign(band, channel);
            }
        }
    }
}

impl EffectProcessor for ParametricEq {
    fn descriptor(&self) -> &'static EffectDescriptor {
        &DESCRIPTOR
    }

    fn prepare(&mut self, sample_rate: f32, max_block: usize, channels: usize) {
        self.sample_rate = if sample_rate > 0.0 {
            sample_rate
        } else {
            48_000.0
        };
        let _ = channels;
        self.max_block = max_block;
        self.dry = alloc::vec![0.0; max_block];
        self.redesign_all();
        self.reset();
    }

    fn process(&mut self, buffer: &mut AudioBuffer<'_>, _ctx: &RenderContext) {
        if self.bypassed {
            return;
        }
        let channels = buffer.channel_count().min(MAX_CHANNELS);
        let frames = buffer.frames();
        if channels == 0 || frames == 0 || frames > self.max_block || frames > self.dry.len() {
            return;
        }

        let output_gain = super::super::util::dsp::db_to_gain(self.output_db);
        let wet = self.wet;

        for channel in 0..channels {
            {
                let Some(source) = buffer.channel(channel) else {
                    continue;
                };
                self.dry[..frames].copy_from_slice(source);
            }

            // Cascade the audible bands. Skipping transparent ones is not just
            // an optimisation: a peaking band at 0 dB still applies its
            // (unity) transfer function, and with seven of them the cumulative
            // rounding is audible as a faint hiss on a quiet passage.
            for band in 0..BAND_COUNT {
                if !self.bands[band].is_audible() {
                    continue;
                }
                let filter = &mut self.state[channel][band].filter;
                filter.process_slice(&mut self.dry[..frames]);
            }

            if let Some(destination) = buffer.channel_mut(channel) {
                for (index, out) in destination.iter_mut().enumerate() {
                    let dry_sample = self.dry.get(index).copied().unwrap_or(0.0);
                    let eq_sample = dry_sample * output_gain;
                    *out = eq_sample * wet + dry_sample * (1.0 - wet);
                }
            }
        }
    }

    fn reset(&mut self) {
        for channel in self.state.iter_mut() {
            for band in channel.iter_mut() {
                band.filter.reset();
            }
        }
    }

    fn latency_samples(&self) -> usize {
        // A cascade of biquads is minimum-phase: no delay to compensate.
        0
    }

    fn parameters(&self) -> &[ParameterDescriptor] {
        &self.table
    }

    fn set_parameter(&mut self, sub: u16, value: f32) {
        let Some(spec) = self.table.get(sub as usize).copied() else {
            return;
        };
        // The band switches are discrete: `value` selects a choice, so it is
        // read from the *unclamped-but-bounded* float rather than the
        // continuous range. `clamp` still guards NaN.
        let value = clamp_parameter(&spec, value);

        if (PARAM_BAND_BASE..PARAM_OUTPUT_DB).contains(&sub) {
            let offset = sub - PARAM_BAND_BASE;
            let band = (offset / PARAMS_PER_BAND) as usize;
            let field = offset % PARAMS_PER_BAND;
            if band >= BAND_COUNT {
                return;
            }
            match field {
                0 => self.bands[band].enabled = value >= 0.5,
                1 => {
                    if let Some(mode) = FilterMode::from_u32(value as u32) {
                        self.bands[band].mode = mode;
                    }
                }
                2 => self.bands[band].frequency_hz = value,
                3 => self.bands[band].gain_db = value,
                4 => self.bands[band].q = value,
                _ => {}
            }
            // A band's *type* decides whether gain or Q even applies, so a
            // redesign always follows.
            for channel in 0..MAX_CHANNELS {
                self.redesign(band, channel);
            }
            return;
        }

        match sub {
            PARAM_OUTPUT_DB => self.output_db = value,
            PARAM_MIX => {
                self.mix_percent = value;
                self.wet = (value / 100.0).clamp(0.0, 1.0);
            }
            _ => {}
        }
    }

    fn get_parameter(&self, sub: u16) -> Option<f32> {
        if (PARAM_BAND_BASE..PARAM_OUTPUT_DB).contains(&sub) {
            let offset = sub - PARAM_BAND_BASE;
            let band = (offset / PARAMS_PER_BAND) as usize;
            let field = offset % PARAMS_PER_BAND;
            let settings = *self.bands.get(band)?;
            return Some(match field {
                0 => f32::from(settings.enabled as u8),
                1 => settings.mode.as_u32() as f32,
                2 => settings.frequency_hz,
                3 => settings.gain_db,
                4 => settings.q,
                _ => return None,
            });
        }
        match sub {
            PARAM_OUTPUT_DB => Some(self.output_db),
            PARAM_MIX => Some(self.mix_percent),
            _ => None,
        }
    }

    fn is_bypassed(&self) -> bool {
        self.bypassed
    }

    fn set_bypassed(&mut self, bypassed: bool) {
        self.bypassed = bypassed;
    }

    fn wet(&self) -> f32 {
        self.wet
    }

    fn set_wet(&mut self, wet: f32) {
        self.wet = sanitize_wet(wet);
        self.mix_percent = self.wet * 100.0;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::effects::util::dsp::sin_poly;
    use core::f32::consts::PI;

    const SR: f32 = 48_000.0;

    fn make() -> ParametricEq {
        let mut effect = ParametricEq::new(ParameterAddress::effect(0, 0, 0));
        effect.prepare(SR, 256, 2);
        effect
    }

    /// Runs a sine through the effect and returns the settled peak.
    fn measure(effect: &mut ParametricEq, hz: f32, frames: usize) -> f32 {
        let chunk = 256;
        let mut peak = 0.0_f32;
        let mut produced = 0;
        while produced < frames {
            let mut channel: alloc::vec::Vec<f32> = (0..chunk)
                .map(|n| sin_poly(2.0 * PI * hz * (produced + n) as f32 / SR))
                .collect();
            {
                let mut views = [&mut channel[..]];
                let mut buf = AudioBuffer::new(&mut views);
                let ctx = RenderContext::new(SR, chunk, produced as i64, 120.0, 960);
                effect.process(&mut buf, &ctx);
            }
            if produced >= chunk * 4 {
                for sample in &channel {
                    peak = peak.max(sample.abs());
                }
            }
            produced += chunk;
        }
        peak
    }

    #[test]
    fn there_are_at_least_seven_bands() {
        // Compile-time constant, so the requirement is checked at compile time.
        const { assert!(BAND_COUNT >= 7, "PLAN section 1.3 requires at least seven bands") };
    }

    #[test]
    fn the_descriptor_reports_every_parameter() {
        let effect = make();
        let d = effect.descriptor();
        assert_eq!(d.key, "parametric_eq");
        assert_eq!(d.category, EffectCategory::Equalizer);
        assert_eq!(d.param_count, PARAM_COUNT);
        assert_eq!(effect.parameters().len(), PARAM_COUNT as usize);
        assert!(!d.has_latency, "an EQ cascade introduces no delay");
    }

    #[test]
    fn the_parameter_table_covers_every_ordinal_exactly_once() {
        let table = parameter_table(ParameterAddress::effect(0, 0, 0));
        for (ordinal, spec) in table.iter().enumerate() {
            assert_eq!(
                spec.address.sub & 0x00FF,
                ordinal as u16,
                "ordinal {ordinal} has a mismatched address"
            );
            assert!(!spec.key.is_empty(), "ordinal {ordinal} has no key");
            assert!(
                spec.min_value <= spec.default_value && spec.default_value <= spec.max_value,
                "ordinal {ordinal} default is outside its range"
            );
        }
    }

    #[test]
    fn band_defaults_spread_across_the_spectrum() {
        let low = default_frequency_for_band(0);
        let high = default_frequency_for_band(BAND_COUNT - 1);
        assert!((low - 80.0).abs() < 1.0, "lowest band should be 80 Hz");
        assert!((high - 12_000.0).abs() < 1.0, "highest band should be 12 kHz");
        // Each band must be above the previous one, or the display overlaps.
        for band in 1..BAND_COUNT {
            assert!(
                default_frequency_for_band(band) > default_frequency_for_band(band - 1),
                "band {band} is not above band {}",
                band - 1
            );
        }
    }

    #[test]
    fn the_outer_bands_are_shelves_and_the_inner_ones_peaking() {
        assert_eq!(default_mode_for_band(0), FilterMode::LowShelf);
        assert_eq!(default_mode_for_band(BAND_COUNT - 1), FilterMode::HighShelf);
        for band in 1..BAND_COUNT - 1 {
            assert_eq!(default_mode_for_band(band), FilterMode::Peaking);
        }
    }

    #[test]
    fn band_ordinals_are_contiguous() {
        assert_eq!(band_ordinal(0, 0), 0);
        assert_eq!(band_ordinal(0, 4), 4);
        assert_eq!(band_ordinal(1, 0), 5);
        assert_eq!(band_ordinal(BAND_COUNT - 1, 4), PARAM_OUTPUT_DB - 1);
        assert_eq!(PARAM_OUTPUT_DB, PARAMS_PER_BAND * BAND_COUNT as u16);
    }

    #[test]
    fn every_band_parameter_round_trips() {
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 3), 6.0);
            assert_eq!(effect.get_parameter(band_ordinal(band, 3)), Some(6.0));
            effect.set_parameter(band_ordinal(band, 4), 2.5);
            assert_eq!(effect.get_parameter(band_ordinal(band, 4)), Some(2.5));
            effect.set_parameter(band_ordinal(band, 2), 440.0);
            assert_eq!(effect.get_parameter(band_ordinal(band, 2)), Some(440.0));
            effect.set_parameter(band_ordinal(band, 0), 0.0);
            assert_eq!(effect.get_parameter(band_ordinal(band, 0)), Some(0.0));
            effect.set_parameter(band_ordinal(band, 1), FilterMode::Notch.as_u32() as f32);
            assert_eq!(
                effect.get_parameter(band_ordinal(band, 1)),
                Some(FilterMode::Notch.as_u32() as f32)
            );
        }
    }

    #[test]
    fn a_flat_eq_is_transparent() {
        // Every band at 0 dB (shelves and peaks) must pass audio unchanged.
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 3), 0.0);
        }
        let peak = measure(&mut effect, 1_000.0, 4_096);
        assert!(
            (peak - 1.0).abs() < 0.01,
            "a flat EQ changed a 1 kHz sine to {peak}"
        );
    }

    #[test]
    fn a_boosted_band_lifts_its_own_frequency_and_not_others() {
        let mut effect = make();
        // Silence every band, then enable and boost the middle one only.
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 0), 0.0);
        }
        let mid = BAND_COUNT / 2;
        let centre = default_frequency_for_band(mid);
        effect.set_parameter(band_ordinal(mid, 0), 1.0);
        effect.set_parameter(band_ordinal(mid, 1), FilterMode::Peaking.as_u32() as f32);
        effect.set_parameter(band_ordinal(mid, 3), 12.0);
        effect.set_parameter(band_ordinal(mid, 4), 2.0);

        let boosted = measure(&mut effect, centre, 8_192);
        effect.reset();
        // Two octaves away the boost must be mostly gone.
        let away = measure(&mut effect, centre * 4.0, 8_192);

        assert!(boosted > 3.0, "centre was only boosted to {boosted}");
        assert!(away < 1.2, "the boost leaked to {away} four octaves up");
    }

    #[test]
    fn a_cut_band_attenuates_its_frequency() {
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 0), 0.0);
        }
        let mid = BAND_COUNT / 2;
        let centre = default_frequency_for_band(mid);
        effect.set_parameter(band_ordinal(mid, 0), 1.0);
        effect.set_parameter(band_ordinal(mid, 1), FilterMode::Peaking.as_u32() as f32);
        effect.set_parameter(band_ordinal(mid, 3), -18.0);
        effect.set_parameter(band_ordinal(mid, 4), 2.0);

        let cut = measure(&mut effect, centre, 8_192);
        assert!(cut < 0.3, "an 18 dB cut left {cut} at the centre frequency");
    }

    #[test]
    fn a_disabled_band_is_skipped_entirely() {
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 0), 0.0);
            effect.set_parameter(band_ordinal(band, 3), 0.0);
        }
        let mid = BAND_COUNT / 2;
        effect.set_parameter(band_ordinal(mid, 3), 18.0);
        // Band is still disabled, so the boost must not apply.
        let peak = measure(&mut effect, default_frequency_for_band(mid), 4_096);
        assert!(
            (peak - 1.0).abs() < 0.05,
            "a disabled band still affected the signal: {peak}"
        );
    }

    #[test]
    fn the_reported_response_matches_a_measurement() {
        // The UI draws `response_db_at`; if it disagreed with what the audio
        // path does, the display would be a lie the user cannot verify.
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 0), 0.0);
        }
        let mid = BAND_COUNT / 2;
        let centre = default_frequency_for_band(mid);
        effect.set_parameter(band_ordinal(mid, 0), 1.0);
        effect.set_parameter(band_ordinal(mid, 1), FilterMode::Peaking.as_u32() as f32);
        effect.set_parameter(band_ordinal(mid, 3), 6.0);
        effect.set_parameter(band_ordinal(mid, 4), 1.5);

        let predicted_db = effect.response_db_at(centre);
        let measured = measure(&mut effect, centre, 8_192);
        let measured_db = crate::effects::util::dsp::gain_to_db(measured);

        assert!(
            (predicted_db - measured_db).abs() < 1.0,
            "display says {predicted_db:.2} dB, audio measures {measured_db:.2} dB"
        );
    }

    #[test]
    fn output_trim_scales_the_result() {
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 3), 0.0);
        }
        effect.set_parameter(PARAM_OUTPUT_DB, -6.0);
        let peak = measure(&mut effect, 1_000.0, 4_096);
        // -6 dB is a linear gain of about 0.501.
        assert!(
            (peak - 0.501).abs() < 0.02,
            "-6 dB trim gave {peak}, expected ~0.5"
        );
    }

    #[test]
    fn parameters_are_clamped_and_nan_safe() {
        let mut effect = make();
        effect.set_parameter(band_ordinal(0, 3), 500.0);
        assert_eq!(effect.get_parameter(band_ordinal(0, 3)), Some(24.0));
        effect.set_parameter(band_ordinal(0, 3), f32::NAN);
        assert_eq!(effect.get_parameter(band_ordinal(0, 3)), Some(0.0));
        effect.set_parameter(band_ordinal(0, 2), f32::NAN);
        assert_eq!(
            effect.get_parameter(band_ordinal(0, 2)),
            Some(default_frequency_for_band(0))
        );
    }

    #[test]
    fn unknown_ordinals_are_ignored() {
        let mut effect = make();
        let before = effect.get_parameter(PARAM_OUTPUT_DB);
        effect.set_parameter(PARAM_COUNT + 10, 5.0);
        assert_eq!(effect.get_parameter(PARAM_OUTPUT_DB), before);
        assert_eq!(effect.get_parameter(PARAM_COUNT + 10), None);
    }

    #[test]
    fn bypass_passes_audio_through() {
        let mut effect = make();
        effect.set_parameter(band_ordinal(0, 3), 24.0);
        effect.set_bypassed(true);
        let mut channel = alloc::vec![0.5_f32; 256];
        let expected = channel.clone();
        {
            let mut views = [&mut channel[..]];
            let mut buf = AudioBuffer::new(&mut views);
            effect.process(&mut buf, &RenderContext::default());
        }
        assert_eq!(channel, expected);
    }

    #[test]
    fn a_seven_band_full_boost_stays_finite() {
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 0), 1.0);
            effect.set_parameter(band_ordinal(band, 3), 24.0);
            effect.set_parameter(band_ordinal(band, 4), 18.0);
        }
        let chunk = 256;
        for round in 0..16 {
            let mut channel = alloc::vec![0.9_f32; chunk];
            {
                let mut views = [&mut channel[..]];
                let mut buf = AudioBuffer::new(&mut views);
                let ctx = RenderContext::new(SR, chunk, (round * chunk) as i64, 120.0, 960);
                effect.process(&mut buf, &ctx);
            }
            for sample in &channel {
                assert!(sample.is_finite(), "seven bands at +24 dB blew up: {sample}");
            }
        }
    }

    #[test]
    fn stereo_channels_keep_independent_filter_state() {
        // A shared history would make the two channels bleed into each other,
        // which is audible as a collapse of the stereo image.
        let mut effect = make();
        for band in 0..BAND_COUNT {
            effect.set_parameter(band_ordinal(band, 0), 0.0);
        }
        effect.set_parameter(band_ordinal(3, 0), 1.0);
        effect.set_parameter(band_ordinal(3, 3), 12.0);

        let mut left = alloc::vec![0.5_f32; 256];
        let mut right = alloc::vec![0.0_f32; 256];
        {
            let mut views = [&mut left[..], &mut right[..]];
            let mut buf = AudioBuffer::new(&mut views);
            let ctx = RenderContext::new(SR, 256, 0, 120.0, 960);
            effect.process(&mut buf, &ctx);
        }
        // The silent channel must stay silent: if state were shared, the left
        // channel's energy would appear on the right.
        for (i, sample) in right.iter().enumerate() {
            assert!(sample.abs() < 1e-9, "right channel leaked at sample {i}: {sample}");
        }
    }

    #[test]
    fn an_oversized_block_is_a_safe_no_op() {
        let mut effect = make();
        let mut channel = alloc::vec![0.5_f32; 512];
        let expected = channel.clone();
        {
            let mut views = [&mut channel[..]];
            let mut buf = AudioBuffer::new(&mut views);
            effect.process(&mut buf, &RenderContext::new(SR, 512, 0, 120.0, 960));
        }
        assert_eq!(channel, expected, "an oversized block must not overrun");
    }

    #[test]
    fn a_peaking_band_at_zero_gain_is_not_audible() {
        let settings = BandSettings {
            enabled: true,
            mode: FilterMode::Peaking,
            frequency_hz: 1_000.0,
            gain_db: 0.0,
            q: 1.0,
        };
        assert!(
            !settings.is_audible(),
            "a flat peaking band should be skipped"
        );
        // A low-pass at 0 dB gain is still doing something.
        let low_pass = BandSettings {
            mode: FilterMode::LowPass,
            ..settings
        };
        assert!(low_pass.is_audible());
    }
}
