import 'package:flutter/material.dart';

import 'envelope.dart';
import 'instrument.dart';

/// Built-in instrument preset data, split out of instrument.dart in S0.
///
/// These are pure data tables; the preset *behaviour* stays on
/// [InstrumentPreset].

const List<InstrumentPreset> kBuiltinPresets = [
  // ── Keyboards ──
  InstrumentPreset(
    id: 'piano',
    name: 'Acoustic Grand Piano',
    description: 'Rich, dynamic grand piano',
    icon: Icons.piano,
    category: InstrumentCategory.keyboard,
    programNumber: 0,
    harmonics: [1.0, 0.8, 0.45, 0.30, 0.18, 0.10, 0.06, 0.03],
    attack: 0.003, decay: 0.4, sustain: 0.25, release: 0.15,
    detuneCents: 0.3, noiseAttack: 0.15, brightnessFactor: 0.5,
  ),
  InstrumentPreset(
    id: 'bright_piano',
    name: 'Bright Acoustic Piano',
    description: 'Bright, cutting piano tone',
    icon: Icons.piano,
    category: InstrumentCategory.keyboard,
    programNumber: 1,
    harmonics: [1.0, 0.9, 0.6, 0.45, 0.30, 0.20, 0.12, 0.08],
    attack: 0.002, decay: 0.35, sustain: 0.20, release: 0.12,
    detuneCents: 0.4, noiseAttack: 0.18, brightnessFactor: 0.6,
  ),
  InstrumentPreset(
    id: 'organ',
    name: 'Church Organ',
    description: 'Full, sustaining pipe organ',
    icon: Icons.toc,
    category: InstrumentCategory.keyboard,
    programNumber: 19,
    harmonics: [1.0, 0.5, 0.8, 0.3, 0.6, 0.2, 0.4, 0.1],
    attack: 0.04, decay: 0.05, sustain: 0.95, release: 0.2,
    detuneCents: 1.0, noiseAttack: 0, brightnessFactor: 0.2,
  ),
  InstrumentPreset(
    id: 'accordion',
    name: 'Accordion',
    description: 'Reedy, expressive accordion',
    icon: Icons.toc,
    category: InstrumentCategory.keyboard,
    programNumber: 21,
    harmonics: [1.0, 0.6, 0.9, 0.4, 0.5, 0.25, 0.2, 0.1],
    attack: 0.01, decay: 0.1, sustain: 0.85, release: 0.05,
    detuneCents: 2.0, noiseAttack: 0, brightnessFactor: 0.3,
  ),

  // ── Strings ──
  InstrumentPreset(
    id: 'guitar',
    name: 'Acoustic Guitar (nylon)',
    description: 'Warm nylon-string guitar',
    icon: Icons.music_note_outlined,
    category: InstrumentCategory.string,
    programNumber: 24,
    harmonics: [1.0, 0.7, 0.3, 0.15, 0.08, 0.04, 0.02, 0.01],
    attack: 0.002, decay: 0.15, sustain: 0.6, release: 0.05,
    detuneCents: 0.5, noiseAttack: 0.12, brightnessFactor: 0.4,
  ),
  InstrumentPreset(
    id: 'steel_guitar',
    name: 'Acoustic Guitar (steel)',
    description: 'Bright steel-string acoustic',
    icon: Icons.music_note_outlined,
    category: InstrumentCategory.string,
    programNumber: 25,
    harmonics: [1.0, 0.8, 0.4, 0.20, 0.12, 0.06, 0.04, 0.02],
    attack: 0.001, decay: 0.12, sustain: 0.55, release: 0.04,
    detuneCents: 0.6, noiseAttack: 0.15, brightnessFactor: 0.5,
  ),
  InstrumentPreset(
    id: 'strings',
    name: 'String Ensemble',
    description: 'Lush, sustaining strings',
    icon: Icons.audiotrack,
    category: InstrumentCategory.string,
    programNumber: 48,
    harmonics: [1.0, 0.5, 0.35, 0.25, 0.18, 0.12, 0.08, 0.05],
    attack: 0.08, decay: 0.2, sustain: 0.85, release: 0.4,
    detuneCents: 3.0, noiseAttack: 0, brightnessFactor: 0.25,
  ),
  InstrumentPreset(
    id: 'pizzicato',
    name: 'Pizzicato Strings',
    description: 'Plucked, short strings',
    icon: Icons.audiotrack,
    category: InstrumentCategory.string,
    programNumber: 45,
    harmonics: [1.0, 0.6, 0.3, 0.15, 0.08, 0.04, 0.02, 0.01],
    attack: 0.001, decay: 0.08, sustain: 0, release: 0.02,
    detuneCents: 0.2, noiseAttack: 0.08, brightnessFactor: 0.3,
  ),

  // ── Bass ──
  InstrumentPreset(
    id: 'bass',
    name: 'Acoustic Bass',
    description: 'Warm upright bass',
    icon: Icons.music_note_outlined,
    category: InstrumentCategory.string,
    programNumber: 32,
    harmonics: [1.0, 0.6, 0.3, 0.12, 0.06, 0.03, 0.015, 0.008],
    attack: 0.005, decay: 0.15, sustain: 0.6, release: 0.08,
    detuneCents: 0.4, noiseAttack: 0.08, brightnessFactor: 0.3,
  ),
  InstrumentPreset(
    id: 'electric_bass',
    name: 'Electric Bass (finger)',
    description: 'Deep, punchy electric bass',
    icon: Icons.music_note_outlined,
    category: InstrumentCategory.string,
    programNumber: 33,
    harmonics: [1.0, 0.7, 0.35, 0.18, 0.10, 0.05, 0.025, 0.012],
    attack: 0.003, decay: 0.12, sustain: 0.65, release: 0.06,
    detuneCents: 0.5, noiseAttack: 0.10, brightnessFactor: 0.35,
  ),

  // ── Brass / Wind ──
  InstrumentPreset(
    id: 'brass',
    name: 'Brass Section',
    description: 'Bold, powerful brass ensemble',
    icon: Icons.music_note_outlined,
    category: InstrumentCategory.wind,
    programNumber: 61,
    harmonics: [1.0, 0.8, 0.6, 0.45, 0.3, 0.2, 0.12, 0.08],
    attack: 0.02, decay: 0.15, sustain: 0.85, release: 0.2,
    detuneCents: 1.5, noiseAttack: 0.05, brightnessFactor: 0.4,
  ),
  InstrumentPreset(
    id: 'trumpet',
    name: 'Trumpet',
    description: 'Bright, piercing trumpet',
    icon: Icons.music_note_outlined,
    category: InstrumentCategory.wind,
    programNumber: 56,
    harmonics: [1.0, 0.9, 0.7, 0.55, 0.4, 0.28, 0.18, 0.10],
    attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.15,
    detuneCents: 0.5, noiseAttack: 0.04, brightnessFactor: 0.45,
  ),

  // ── Synth ──
  InstrumentPreset(
    id: 'synth',
    name: 'Synth Lead',
    description: 'Pulsing, cutting synth lead',
    icon: Icons.electric_bolt,
    category: InstrumentCategory.synth,
    programNumber: 80,
    harmonics: [1.0, 0.4, 0.6, 0.2, 0.4, 0.1, 0.2, 0.05],
    attack: 0.005, decay: 0.1, sustain: 0.9, release: 0.05,
    detuneCents: 1.5, noiseAttack: 0, brightnessFactor: 0.2,
  ),
  InstrumentPreset(
    id: 'pad',
    name: 'Synth Pad',
    description: 'Warm, evolving synth pad',
    icon: Icons.waves,
    category: InstrumentCategory.synth,
    programNumber: 88,
    harmonics: [1.0, 0.3, 0.5, 0.2, 0.35, 0.15, 0.25, 0.1],
    attack: 0.3, decay: 0.3, sustain: 0.9, release: 0.8,
    detuneCents: 5.0, noiseAttack: 0, brightnessFactor: 0.15,
  ),
  InstrumentPreset(
    id: 'warm_pad',
    name: 'Warm Pad',
    description: 'Soft, warm analog pad',
    icon: Icons.waves,
    category: InstrumentCategory.synth,
    programNumber: 89,
    harmonics: [1.0, 0.4, 0.2, 0.1, 0.05, 0.025, 0.012, 0.006],
    attack: 0.2, decay: 0.2, sustain: 0.95, release: 0.6,
    detuneCents: 4.0, noiseAttack: 0, brightnessFactor: 0.1,
  ),
];

final List<InstrumentPreset> kSynthPresets = [
  InstrumentPreset(
    id: 'syn_sub_bass',
    name: 'Sub Bass',
    description: 'Subtractive: filtered saw bass',
    icon: Icons.graphic_eq,
    category: InstrumentCategory.synth,
    programNumber: 38,
    harmonics: [1.0],
    synthEngine: 'subtractive',
    attack: 0.004, decay: 0.35, sustain: 0.5, release: 0.12,
    detuneCents: 8, noiseAttack: 0.04,
    filterCutoff: 300, filterResonance: 1.6, filterEnvAmount: 4.0,
    filterAttack: 0.004, filterDecay: 0.35, filterSustain: 0.35,
  ),
  InstrumentPreset(
    id: 'syn_acid',
    name: 'Acid Lead',
    description: 'Subtractive: resonant acid lead',
    icon: Icons.electric_bolt,
    category: InstrumentCategory.synth,
    programNumber: 81,
    harmonics: [1.0],
    synthEngine: 'subtractive',
    attack: 0.002, decay: 0.3, sustain: 0.55, release: 0.08,
    detuneCents: 6,
    filterCutoff: 420, filterResonance: 6.0, filterEnvAmount: 6.0,
    filterAttack: 0.002, filterDecay: 0.28, filterSustain: 0.12,
  ),
  InstrumentPreset(
    id: 'syn_brass_stab',
    name: 'Brass Stab',
    description: 'Subtractive: punchy filtered stab',
    icon: Icons.flash_on,
    category: InstrumentCategory.synth,
    programNumber: 62,
    harmonics: [1.0],
    synthEngine: 'subtractive',
    attack: 0.02, decay: 0.22, sustain: 0.5, release: 0.18,
    detuneCents: 12, noiseAttack: 0.06,
    filterCutoff: 700, filterResonance: 2.0, filterEnvAmount: 3.2,
    filterAttack: 0.02, filterDecay: 0.25, filterSustain: 0.4,
  ),
  InstrumentPreset(
    id: 'syn_supersaw',
    name: 'Super Saw',
    description: 'Wavetable: wide detuned saw stack',
    icon: Icons.waves,
    category: InstrumentCategory.synth,
    programNumber: 82,
    harmonics: [1.0],
    synthEngine: 'wavetable',
    attack: 0.01, decay: 0.3, sustain: 0.8, release: 0.4,
    detuneCents: 22,
  ),
  InstrumentPreset(
    id: 'syn_morph_pad',
    name: 'Morph Wave',
    description: 'Wavetable: slow morphing pad',
    icon: Icons.auto_awesome,
    category: InstrumentCategory.synth,
    programNumber: 89,
    harmonics: [1.0],
    synthEngine: 'wavetable',
    attack: 0.35, decay: 0.4, sustain: 0.9, release: 0.9,
    detuneCents: 14,
    morphRate: 3.0,
    envCurve: EnvelopeCurve(points: [
      EnvelopePoint(x: 0, y: 0, curve: 0.5),
      EnvelopePoint(x: 0.25, y: 1, curve: -0.3),
      EnvelopePoint(x: 0.8, y: 0.8),
      EnvelopePoint(x: 1, y: 0, curve: 0.3),
    ]),
  ),
  InstrumentPreset(
    id: 'syn_fm_bell',
    name: 'FM Bell',
    description: 'FM 2-op: metallic bell',
    icon: Icons.notifications_active_outlined,
    category: InstrumentCategory.synth,
    programNumber: 9,
    harmonics: [1.0],
    synthEngine: 'fm',
    attack: 0.001, decay: 1.6, sustain: 0.0, release: 1.2,
    fmRatio: 3.01, fmIndex: 5.5, fmDecay: 1.1, fmFeedback: 0.2,
  ),
  InstrumentPreset(
    id: 'syn_fm_ep',
    name: 'FM E.Piano',
    description: 'FM 2-op: electric piano',
    icon: Icons.piano,
    category: InstrumentCategory.keyboard,
    programNumber: 4,
    harmonics: [1.0],
    synthEngine: 'fm',
    attack: 0.002, decay: 1.0, sustain: 0.35, release: 0.4,
    fmRatio: 1.0, fmIndex: 2.4, fmDecay: 0.55, fmFeedback: 0.12,
  ),
  InstrumentPreset(
    id: 'syn_grain_pad',
    name: 'Granular Cloud',
    description: 'Granular: shimmering particle pad',
    icon: Icons.blur_on,
    category: InstrumentCategory.synth,
    programNumber: 98,
    harmonics: [1.0],
    synthEngine: 'granular',
    attack: 0.3, decay: 0.5, sustain: 0.85, release: 1.0,
    detuneCents: 10,
  ),
];
